export interface Database {
  public: {
    Tables: {
      profissionais: {
        Row: {
          id: string;
          nome: string;
          email: string;
          telefone: string | null;
          whatsapp: string | null;
          especialidades: string[] | null;
          experiencia: string | null;
          sobre: string | null;
          foto_url: string | null;
          ocupacao: string;
          estado: string;
          cidade: string;
          created_at: string;
          updated_at: string;
          user_id: string;
          slug: string | null;
        };
        Insert: {
          id?: string;
          nome: string;
          email: string;
          telefone?: string | null;
          whatsapp?: string | null;
          especialidades?: string[] | null;
          experiencia?: string | null;
          sobre?: string | null;
          foto_url?: string | null;
          ocupacao: string;
          estado: string;
          cidade: string;
          created_at?: string;
          updated_at?: string;
          user_id: string;
          slug?: string | null;
        };
        Update: {
          id?: string;
          nome?: string;
          email?: string;
          telefone?: string | null;
          whatsapp?: string | null;
          especialidades?: string[] | null;
          experiencia?: string | null;
          sobre?: string | null;
          foto_url?: string | null;
          ocupacao?: string;
          estado?: string;
          cidade?: string;
          created_at?: string;
          updated_at?: string;
          user_id?: string;
          slug?: string | null;
        };
      };
      jobs: {
        Row: {
          id: string;
          title: string;
          description: string;
          requirements: string[];
          benefits: string[] | null;
          salary: string | null;
          type: string;
          location: string;
          businessId: string;
          expiresAt: string | null;
          status: string;
          featured: boolean;
          views: number;
          applications: number;
          tags: string[] | null;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          requirements: string[];
          benefits?: string[] | null;
          salary?: string | null;
          type: string;
          location: string;
          businessId: string;
          expiresAt?: string | null;
          status?: string;
          featured?: boolean;
          views?: number;
          applications?: number;
          tags?: string[] | null;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          requirements?: string[];
          benefits?: string[] | null;
          salary?: string | null;
          type?: string;
          location?: string;
          businessId?: string;
          expiresAt?: string | null;
          status?: string;
          featured?: boolean;
          views?: number;
          applications?: number;
          tags?: string[] | null;
          createdAt?: string;
          updatedAt?: string;
        };
      };
      job_applications: {
        Row: {
          id: string;
          job_id: string;
          professional_id: string;
          status: string;
          cover_letter: string | null;
          resume_url: string | null;
          portfolio_url: string | null;
          salary_expectation: number | null;
          availability_date: string | null;
          experience_years: number | null;
          skills: string[] | null;
          additional_info: Record<string, any> | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          job_id: string;
          professional_id: string;
          status?: string;
          cover_letter?: string | null;
          resume_url?: string | null;
          portfolio_url?: string | null;
          salary_expectation?: number | null;
          availability_date?: string | null;
          experience_years?: number | null;
          skills?: string[] | null;
          additional_info?: Record<string, any> | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          job_id?: string;
          professional_id?: string;
          status?: string;
          cover_letter?: string | null;
          resume_url?: string | null;
          portfolio_url?: string | null;
          salary_expectation?: number | null;
          availability_date?: string | null;
          experience_years?: number | null;
          skills?: string[] | null;
          additional_info?: Record<string, any> | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
    };
  };
} 