-- Inserir profissionais de exemplo
INSERT INTO profissionais 
(name, slug, ocupacao, descricao, foto, endereco, telefone, estado, cidade, email, website, redes_sociais, disponibilidade, is_featured, avaliacao, status)
VALUES
(
    'Ana Silva', 
    'ana-silva', 
    'Médica',
    'Médica especialista em clínica geral com mais de 10 anos de experiência. Atendimento humanizado e focado no bem-estar do paciente.',
    'https://example.com/fotos/ana-silva.jpg',
    'Rua da Saúde, 123, Centro',
    '(11) 99999-1111',
    'SP',
    'São Paulo',
    'contato@anasilva.med.br',
    'https://anasilva.med.br',
    '{"facebook": "https://facebook.com/draanasilva", "instagram": "https://instagram.com/draanasilva", "linkedin": "https://linkedin.com/in/draanasilva"}',
    '{"segunda": "08:00 - 18:00", "terca": "08:00 - 18:00", "quarta": "08:00 - 18:00", "quinta": "08:00 - 18:00", "sexta": "08:00 - 16:00", "sabado": null, "domingo": null}',
    true,
    4.8,
    'APPROVED'
),
(
    'Carlos Oliveira', 
    'carlos-oliveira', 
    'Advogado',
    'Advogado especializado em direito civil e trabalhista. Atendimento personalizado para pessoas físicas e jurídicas.',
    'https://example.com/fotos/carlos-oliveira.jpg',
    'Avenida Paulista, 1000, Sala 203',
    '(11) 98888-2222',
    'SP',
    'São Paulo',
    'carlos@oliveira.adv.br',
    'https://oliveira.adv.br',
    '{"facebook": "https://facebook.com/carlosoliveira.adv", "instagram": "https://instagram.com/carlosoliveira.adv"}',
    '{"segunda": "09:00 - 17:00", "terca": "09:00 - 17:00", "quarta": "09:00 - 17:00", "quinta": "09:00 - 17:00", "sexta": "09:00 - 17:00", "sabado": null, "domingo": null}',
    true,
    4.6,
    'APPROVED'
),
(
    'Mariana Souza', 
    'mariana-souza', 
    'Arquiteta',
    'Arquiteta e urbanista com foco em projetos residenciais e comerciais sustentáveis. Transforma espaços em ambientes funcionais e aconchegantes.',
    'https://example.com/fotos/mariana-souza.jpg',
    'Rua dos Arquitetos, 456, Jardins',
    '(11) 97777-3333',
    'SP',
    'São Paulo',
    'contato@marianasouza.arq.br',
    'https://marianasouza.arq.br',
    '{"facebook": "https://facebook.com/marianasouza.arq", "instagram": "https://instagram.com/marianasouza.arq", "pinterest": "https://pinterest.com/marianasouza"}',
    '{"segunda": "10:00 - 18:00", "terca": "10:00 - 18:00", "quarta": "10:00 - 18:00", "quinta": "10:00 - 18:00", "sexta": "10:00 - 16:00", "sabado": "10:00 - 14:00", "domingo": null}',
    false,
    4.9,
    'APPROVED'
),
(
    'Pedro Santos', 
    'pedro-santos', 
    'Professor Particular',
    'Professor de matemática e física para ensino médio e preparação para vestibular. Metodologia focada na compreensão dos conceitos e resolução de problemas.',
    'https://example.com/fotos/pedro-santos.jpg',
    null,
    '(11) 96666-4444',
    'SP',
    'São Paulo',
    'pedro.professor@email.com',
    null,
    '{"instagram": "https://instagram.com/pedroprof", "whatsapp": "5511966664444"}',
    '{"segunda": "14:00 - 20:00", "terca": "14:00 - 20:00", "quarta": "14:00 - 20:00", "quinta": "14:00 - 20:00", "sexta": "14:00 - 18:00", "sabado": "09:00 - 12:00", "domingo": null}',
    false,
    4.7,
    'APPROVED'
),
(
    'Julia Rodrigues', 
    'julia-rodrigues', 
    'Designer',
    'Designer gráfica especializada em identidade visual, branding e design para mídias sociais. Criando soluções visuais que fortalecem a presença da sua marca.',
    'https://example.com/fotos/julia-rodrigues.jpg',
    'Rua das Artes, 789, Vila Madalena',
    '(11) 95555-5555',
    'SP',
    'São Paulo',
    'julia@design.com',
    'https://juliadesign.com',
    '{"instagram": "https://instagram.com/juliadesign", "behance": "https://behance.net/juliadesign", "linkedin": "https://linkedin.com/in/juliadesign"}',
    '{"segunda": "09:00 - 18:00", "terca": "09:00 - 18:00", "quarta": "09:00 - 18:00", "quinta": "09:00 - 18:00", "sexta": "09:00 - 18:00", "sabado": null, "domingo": null}',
    true,
    4.5,
    'APPROVED'
),
(
    'Roberto Almeida', 
    'roberto-almeida', 
    'Eletricista',
    'Eletricista residencial e comercial com mais de 15 anos de experiência. Instalações, reparos e manutenção preventiva com segurança e qualidade.',
    'https://example.com/fotos/roberto-almeida.jpg',
    null,
    '(11) 94444-6666',
    'SP',
    'São Paulo',
    'roberto.eletricista@email.com',
    null,
    '{"facebook": "https://facebook.com/robertoeletricista", "whatsapp": "5511944446666"}',
    '{"segunda": "08:00 - 18:00", "terca": "08:00 - 18:00", "quarta": "08:00 - 18:00", "quinta": "08:00 - 18:00", "sexta": "08:00 - 18:00", "sabado": "08:00 - 12:00", "domingo": null}',
    false,
    4.2,
    'APPROVED'
),
(
    'Fernanda Lima', 
    'fernanda-lima', 
    'Nutricionista',
    'Nutricionista especializada em reeducação alimentar e emagrecimento saudável. Atendimento humanizado com planos alimentares personalizados.',
    'https://example.com/fotos/fernanda-lima.jpg',
    'Avenida da Saúde, 321, Pinheiros',
    '(11) 93333-7777',
    'SP',
    'São Paulo',
    'fernanda@nutricao.com',
    'https://fernandanutri.com.br',
    '{"instagram": "https://instagram.com/fernandanutri", "facebook": "https://facebook.com/fernandanutri"}',
    '{"segunda": "08:00 - 17:00", "terca": "08:00 - 17:00", "quarta": "08:00 - 17:00", "quinta": "08:00 - 17:00", "sexta": "08:00 - 15:00", "sabado": null, "domingo": null}',
    true,
    4.8,
    'APPROVED'
),
(
    'Lucas Mendes', 
    'lucas-mendes', 
    'Fotógrafo',
    'Fotógrafo profissional especializado em eventos, casamentos e ensaios. Captando momentos especiais com um olhar único e sensível.',
    'https://example.com/fotos/lucas-mendes.jpg',
    null,
    '(11) 92222-8888',
    'SP',
    'São Paulo',
    'contato@lucasmendesfotografia.com',
    'https://lucasmendesfotografia.com',
    '{"instagram": "https://instagram.com/lucasmendesfoto", "facebook": "https://facebook.com/lucasmendesfoto"}',
    null,
    false,
    4.6,
    'APPROVED'
); 