-- Inserir dados de exemplo para profissionais
INSERT INTO profissionais 
(nome, ocupacao, especialidades, experiencia, educacao, certificacoes, 
portfolio, disponibilidade, valor_hora, sobre, foto, telefone, email, 
website, endereco, cidade, estado, social_media, status, featured)
VALUES
(
    'Ana Silva', 
    'Médica',
    ARRAY['Clínica Geral', 'Pediatria', 'Medicina Preventiva'],
    'Mais de 10 anos atuando em hospitais públicos e privados com foco em medicina familiar.',
    ARRAY['Graduação em Medicina - USP', 'Residência em Clínica Médica - Hospital das Clínicas', 'Especialização em Pediatria - Instituto da Criança'],
    ARRAY['CRM/SP 12345', 'Certificação em Primeiros Socorros'],
    ARRAY['https://dranasilvaclinica.com.br/casos', 'https://dranasilvaclinica.com.br/publicacoes'],
    'Segunda a Sexta, 8h às 18h',
    250.00,
    'Médica dedicada com abordagem humanizada, focada no bem-estar integral dos pacientes. Trabalho com prevenção e tratamento personalizado.',
    'https://randomuser.me/api/portraits/women/1.jpg',
    '(11) 98765-4321',
    'dra.anasilva@exemplo.com.br',
    'https://dranasilvaclinica.com.br',
    'Rua das Flores, 123, Conjunto 45',
    'São Paulo',
    'SP',
    '{"instagram": "@dra.anasilva", "linkedin": "anasilvamedica", "facebook": "draanasilva"}',
    'APPROVED',
    true
),
(
    'Carlos Oliveira', 
    'Advogado',
    ARRAY['Direito Civil', 'Direito do Trabalho', 'Direito do Consumidor'],
    'Mais de 15 anos de experiência em escritórios de grande porte e como assessor jurídico empresarial.',
    ARRAY['Graduação em Direito - PUC-SP', 'Especialização em Direito Civil - FGV', 'Mestrado em Direito do Trabalho - USP'],
    ARRAY['OAB/SP 54321', 'Especialista em Mediação e Arbitragem'],
    ARRAY['https://oliveiralegal.com.br/casos/trabalhista', 'https://oliveiralegal.com.br/artigos'],
    'Segunda a Sexta, 9h às 18h',
    300.00,
    'Advogado com vasta experiência em questões civis e trabalhistas. Atendimento personalizado e abordagem estratégica para soluções jurídicas eficazes.',
    'https://randomuser.me/api/portraits/men/2.jpg',
    '(11) 91234-5678',
    'carlos@oliveiralegal.com.br',
    'https://oliveiralegal.com.br',
    'Avenida Paulista, 1000, Sala 1520',
    'São Paulo',
    'SP',
    '{"instagram": "@adv.carlos", "linkedin": "carlosoliveira_adv", "facebook": "advcarlosoliveira"}',
    'APPROVED',
    true
),
(
    'Mariana Souza', 
    'Arquiteta',
    ARRAY['Arquitetura Residencial', 'Arquitetura Sustentável', 'Interiores'],
    'Mais de 8 anos desenvolvendo projetos residenciais e comerciais com foco em sustentabilidade.',
    ARRAY['Graduação em Arquitetura - Mackenzie', 'Pós-graduação em Arquitetura Sustentável - IED São Paulo'],
    ARRAY['CAU A12345-6', 'Certificação LEED Green Associate'],
    ARRAY['https://marianasouza.arq.br/portfolio/residencial', 'https://marianasouza.arq.br/portfolio/comercial'],
    'Segunda a Sexta, 10h às 19h',
    180.00,
    'Arquiteta apaixonada por criar espaços harmoniosos e funcionais. Especialista em projetos sustentáveis que unem estética, conforto e responsabilidade ambiental.',
    'https://randomuser.me/api/portraits/women/3.jpg',
    '(11) 99876-5432',
    'contato@marianasouza.arq.br',
    'https://marianasouza.arq.br',
    'Rua Augusta, 789, Conjunto 32',
    'São Paulo',
    'SP',
    '{"instagram": "@mariana.arq", "pinterest": "marianasouzaarq", "facebook": "marianasouzaarquitetura"}',
    'APPROVED',
    true
),
(
    'Roberto Almeida', 
    'Eletricista',
    ARRAY['Instalações Residenciais', 'Instalações Comerciais', 'Manutenção Preventiva'],
    'Mais de 20 anos trabalhando com instalações elétricas de todos os portes.',
    ARRAY['Técnico em Eletrotécnica - SENAI', 'Curso de NR-10 - Segurança em Instalações Elétricas'],
    ARRAY['Certificação NR-10', 'Credenciado pela ENEL'],
    ARRAY['https://eletricistaroberto.com.br/projetos'],
    'Todos os dias, 7h às 21h',
    80.00,
    'Eletricista com vasta experiência em instalações e manutenções. Trabalho com segurança e qualidade, priorizando a satisfação do cliente e soluções duradouras.',
    'https://randomuser.me/api/portraits/men/4.jpg',
    '(11) 97654-3210',
    'roberto@eletricistaroberto.com.br',
    'https://eletricistaroberto.com.br',
    'Rua dos Eletricistas, 456',
    'São Paulo',
    'SP',
    '{"instagram": "@roberto.eletricista", "facebook": "robertoeletricista"}',
    'APPROVED',
    false
),
(
    'Fernanda Lima', 
    'Nutricionista',
    ARRAY['Nutrição Clínica', 'Nutrição Esportiva', 'Reeducação Alimentar'],
    'Mais de 6 anos atendendo em consultório próprio e assessorando atletas amadores e profissionais.',
    ARRAY['Graduação em Nutrição - UNIFESP', 'Especialização em Nutrição Esportiva - USP'],
    ARRAY['CRN-3 12345', 'Especialista em Nutrição Funcional'],
    ARRAY['https://fernandalima.nutri.br/casos-de-sucesso', 'https://fernandalima.nutri.br/artigos'],
    'Segunda a Sexta, 8h às 20h',
    150.00,
    'Nutricionista especializada em planos alimentares personalizados. Atendo com foco na saúde integral e bem-estar, respeitando a individualidade e os objetivos de cada pessoa.',
    'https://randomuser.me/api/portraits/women/5.jpg',
    '(11) 95432-1098',
    'fernanda@nutricionista.com.br',
    'https://fernandalima.nutri.br',
    'Avenida Brasil, 500, Sala 45',
    'São Paulo',
    'SP',
    '{"instagram": "@fernanda.nutri", "youtube": "fernandalimanutricionista", "facebook": "nutrifernandalima"}',
    'APPROVED',
    false
),
(
    'Pedro Santos', 
    'Professor Particular',
    ARRAY['Matemática', 'Física', 'Cálculo', 'Estatística'],
    'Mais de 10 anos lecionando para ensino médio e preparando alunos para vestibulares e ENEM.',
    ARRAY['Licenciatura em Matemática - UNESP', 'Mestrado em Ensino de Ciências - USP'],
    ARRAY['Especialização em Metodologias Ativas'],
    ARRAY['https://professorpedro.edu.br/resultados'],
    'Segunda a Sábado, 14h às 20h',
    90.00,
    'Professor experiente com método personalizado de ensino. Especialista em tornar conteúdos complexos acessíveis, com foco em estratégias para exames e concursos.',
    'https://randomuser.me/api/portraits/men/6.jpg',
    '(11) 94321-5678',
    'pedro@professorparticular.com.br',
    'https://professorpedro.edu.br',
    'Rua Itapeva, 200, Apto 102',
    'São Paulo',
    'SP',
    '{"instagram": "@prof.pedromatematica", "youtube": "professorpedro", "facebook": "professorpedromatematica"}',
    'PENDING',
    false
),
(
    'Julia Rodrigues', 
    'Designer Gráfica',
    ARRAY['Identidade Visual', 'Design Editorial', 'Social Media'],
    'Mais de 7 anos desenvolvendo projetos de branding e comunicação visual para empresas de diversos setores.',
    ARRAY['Bacharelado em Design - FAAP', 'Especialização em Branding - Istituto Europeo di Design'],
    ARRAY['Adobe Certified Expert'],
    ARRAY['https://juliarodrigues.design/projetos/branding', 'https://juliarodrigues.design/projetos/editorial'],
    'Segunda a Sexta, 9h às 18h',
    120.00,
    'Designer apaixonada por criar identidades visuais marcantes. Trabalho com foco na comunicação eficiente da essência de cada marca, alinhando estética e estratégia.',
    'https://randomuser.me/api/portraits/women/7.jpg',
    '(11) 96543-2109',
    'contato@juliarodrigues.design',
    'https://juliarodrigues.design',
    'Rua Oscar Freire, 1500, Studio 5',
    'São Paulo',
    'SP',
    '{"instagram": "@julia.design", "behance": "juliarodriguesdesign", "linkedin": "juliarodriguesdesign"}',
    'APPROVED',
    false
),
(
    'Lucas Mendes', 
    'Fotógrafo',
    ARRAY['Fotografia de Eventos', 'Retratos', 'Fotografia Corporativa'],
    'Mais de 12 anos capturando momentos especiais em eventos sociais e corporativos.',
    ARRAY['Tecnólogo em Fotografia - SENAC', 'Especialização em Fotografia Digital Avançada - IED São Paulo'],
    ARRAY['Membro da Associação Brasileira de Fotógrafos de Eventos'],
    ARRAY['https://lucasmendesfotografia.com.br/casamentos', 'https://lucasmendesfotografia.com.br/corporativo'],
    'Todos os dias, mediante agendamento',
    200.00,
    'Fotógrafo especializado em capturar momentos autênticos e emoções verdadeiras. Trabalho com sensibilidade e técnica para criar imagens que contam histórias e preservam memórias.',
    'https://randomuser.me/api/portraits/men/8.jpg',
    '(11) 98765-4321',
    'lucas@fotografo.com.br',
    'https://lucasmendesfotografia.com.br',
    'Rua da Consolação, 2500, Studio 12',
    'São Paulo',
    'SP',
    '{"instagram": "@lucasmendesfoto", "facebook": "lucasmendesfotografia", "pinterest": "lucasmendesfotografia"}',
    'REJECTED',
    false
); 